sudo: required

services:
  - docker

script:
  - docker build -t kin-server .
  - docker run --name kin -d kin-server
  - echo "Container has been started... waiting a few seconds for initialization!"
  - travis_wait sleep 15
  - docker exec kin bash -c "apt-get update && apt-get install curl -y --no-install-recommends && curl -f https://localhost:8080"
  - docker logs kin
